name: Continuous Integration

on:
  push:
    branches:
      - canary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add other steps as needed for the CI workflow
